Revert "Do not use deprecated LLVM Typed pointer functions"
This reverts commit 4fa1cd56cae62acb63b7fc9c264826b54713248f.

Reason for revert: Fails macOS ARM64 build when rolling into ANGLE

```
../../third_party/SwiftShader/src/Reactor/LLVMReactor.cpp:636:37: error: no member named 'getPtrTy' in 'llvm::IRBuilder<>'
  636 |                 llvm::Type *ptrTy = jit->builder->getPtrTy();
```

Example failing roll:

https://chromium-review.git.corp.google.com/c/angle/angle/+/8183864

Error log:

https://logs.chromium.org/logs/angle/buildbucket/cr-buildbucket/8674489614448676433/+/u/compile__with_patch_/raw_io.output_text_failure_summary_

Change-Id: Idcfcc58e24a657bae2574a7285d35b2b977d74f2
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/77668
Tested-by: Shahbaz Youssefi <syoussefi@google.com>
Reviewed-by: Shahbaz Youssefi <syoussefi@google.com>
Commit-Queue: Shahbaz Youssefi <syoussefi@google.com>
Reviewed-by: Geoff Lang <geofflang@google.com>